package organization;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

import users.User;
import users.Student;
import users.Teacher;
import users.Employee;
import users.Manager;
import storage.DataStorage;

public class Report implements Serializable {
    private static final long serialVersionUID = 1L;

    private Manager createdBy;
    private Date createdDate;
    private String content;

    public Report(Manager m) {
        if (m == null) throw new IllegalArgumentException("Manager cannot be null");
        this.createdBy = m;
        this.createdDate = new Date();
        this.content = generateContent();
    }

    private String generateContent() {
        StringBuilder sb = new StringBuilder();
        sb.append("\n----------- ACADEMIC PERFORMANCE REPORT -----------\n");
        sb.append("Generated by: ").append(createdBy.getFullName()).append("\n");
        sb.append("Date: ").append(createdDate).append("\n");
        sb.append("--------------------------------------------------\n");

        List<User> users = DataStorage.getInstance().getUsers();
        int students = 0, teachers = 0, employees = 0;
        double totalGpa = 0;

        for (User u : users) {
            if (u instanceof Student) {
                students++;
                totalGpa += ((Student) u).getGpa();
            } else if (u instanceof Teacher) {
                teachers++;
            } else if (u instanceof Employee) {
                employees++;
            }
        }
        sb.append("Total students: ").append(students).append("\n");
        sb.append("Total teachers: ").append(teachers).append("\n");
        sb.append("Total other employees: ").append(employees).append("\n");
        if (students > 0) {
            sb.append(String.format("Average GPA: %.2f%n", totalGpa / students));
        }
        sb.append("--------------------------------------------------\n");
        return sb.toString();
    }

    public String getContent() { return content; }
    public Manager getCreatedBy() { return createdBy; }
    public Date getCreatedDate() { return new Date(createdDate.getTime()); }

    @Override
    public String toString() {
        return content;
    }
}
